### ISSUE TITLE
Nova versão com as mudanças no nome da classe de response

### ISSUE THREAD

**Issue by marciodojr** [totalvoice/totalvoice-php#17]
@dilowagner, Olá, poderia publicar uma nova versão de patch com as mudanças desse merge request?

https://github.com/totalvoice/totalvoice-php/commit/b701912b52d47bfa4a737f152e33c8901cbfb4df

Acredito que a versão 1.15.1 ainda não tenha essa mudança.

https://github.com/totalvoice/totalvoice-php/blob/1.15.1/test/Handler/ResponseTest.php

**Comment by dilowagner** [comment]
Opa, obrigado @marciodojr 
vou gerar uma nova versao

**Comment by dilowagner** [comment]
[Versao 1.15.2](https://github.com/totalvoice/totalvoice-php/releases/tag/1.15.2)
