### ISSUE TITLE
Rota incorreta na Classe de Composto

### ISSUE THREAD

**Issue by soujhony** [totalvoice/totalvoice-php#3]
A rota na classe de composto, esta configurada para **composo** dando erro no acesso da api que é **composto**

**Comment by carloshenriqueds** [comment]
Olá @jhonystein tudo bem contigo?

Obrigado pelo retorno, corrigimos este bug e já está funcionando na versão: 1.0.7

Basta dar um composer update no seu projeto.

Até a próxima :)
