### ISSUE TITLE
Método HTTP errado

### ISSUE THREAD

**Issue by soujhony** [totalvoice/totalvoice-php#4]
Na classe Chamada o método HTTP do método **escutar** esta GET, quando deveria estar POST, conforme documentação da API da Totalvoice. ;-)

**Comment by carloshenriqueds** [comment]
Olá @jhonystein tudo bem contigo?

Obrigado pelo retorno, corrigimos este bug e já está funcionando na versão: 1.0.8

Basta modificar seu composer para a versão 1.0.8 e executar:
`composer update`

Abraço
