### ISSUE TITLE
Constante da Rota errada nos métodos da Fila

### ISSUE THREAD

**Issue by dilowagner** [totalvoice/totalvoice-php#7]
Alterar o ROTA_RAMAL para ROTA_FILA nos métodos de exclusão e busca de ramais na fila.

https://github.com/totalvoice/totalvoice-php/blob/master/src/Api/Fila.php#L89
https://github.com/totalvoice/totalvoice-php/blob/master/src/Api/Fila.php#L99

**Comment by raphaelmacsabpf** [comment]
Issue fechada, pois já foi resolvida.
